name = "landing-page"
compatibility_date = "2025-06-15"

[build]
command = "npm run build"

[site]
bucket = ".svelte-kit/cloudflare"

[deploy]
# this tells wrangler where to deploy from
main = ".svelte-kit/cloudflare/_worker.js"
